### ISSUE TITLE
PROGRAM DISPLAYS JAVA EXCEPTION FOR INVALID COMMAND LINE ARGS

### ISSUE THREAD

**Issue by ukattah** [wonsunahn/CS1632_Spring2024#2]
IDENTIFIER: BUG-ARGS-INVALID
SUMMARY: Java exception displayed when it shouldn't.
DESCRIPTION: When an invalid arg is passed into the command line, a Java exception is displayed. 
REPRODUCTION STEPS: Preconditions: "Java version" shows JRE 11 installed on the path variable.
EXPECTED BEHAVIOR: In the event of an invalid command line arg, the system should explain the reason that it cannot run and shut down. At no point should a java exception be displayed. 
OBSERVED BEHAVIOR: The following output is displayed in the command line with the following command:
- "java -jar GoatGoatCar.jar car goat 10001 l"
- Exception in thread "main" java.lang.NumberFormatException: For input string: "l"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at GoatGoatCar.main(GoatGoatCar.java:180)

**Comment by ukattah** [comment]
Java exception with command line args shouldn't display.
